import Head from "next/head";
import Link from "next/link";
import { SignInButton, UserButton, useUser } from "@clerk/nextjs";

import { api } from "@/utils/api";

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });

  const user = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="h-screen bg-red-300">
          <h1 className="text-3xl font-bold">Hello from tRPC</h1>
          {!!user.isSignedIn && <UserButton />}
          {!user.isSignedIn && (
            <SignInButton>
              <button>Sign in with Clerk</button>
            </SignInButton>
          )}
        </div>
      </main>
    </>
  );
}
